### ISSUE TITLE
Using the flashFile parameter in preset.xml file

### ISSUE THREAD

**Issue by CurtisFissel** [zkemble/AVRDUDESS#5]
Hello!

I have one of my own presets made... But I cant get the flashFile parameter to work.

Here is what I am trying... I'm sure I am missing something simple.
`<flashFile />C:\firmware.hex</flashFile>` 

Thank you for any help.

Curtis

**Comment by zkemble** [comment]
Hi, that first bit with `<flashFile />` is short for `<flashFile></flashFile>` (empty parameter) so with yours you've ended up with `<flashFile></flashFile>C:\firmware.hex</flashFile>`.
Try this `<flashFile>C:\firmware.hex</flashFile>`.

Also, you would normally setup your preset using the AVRDUDESS program rather than manually editing the presets.xml file.

**Comment by CurtisFissel** [comment]
Thank you very much. Got it figured out :)
